# Generated by Django 3.2.4 on 2021-07-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0002_auto_20210708_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeeds.post'),
        ),
    ]
