# Generated by Django 3.2.4 on 2013-01-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210708_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
